using System.Text.Json;
using AiReporting.Api.Application.AiReports.Authorization;
using AiReporting.Api.Application.AiReports.Execution;
using AiReporting.Api.Application.AiReports.Forecasting;
using AiReporting.Api.Application.AiReports.Intent;
using AiReporting.Api.Application.AiReports.QueryBuilding;
using AiReporting.Api.Application.AiReports.ReportWriting;
using AiReporting.Api.Application.AiReports.Validation;
using AiReporting.Api.Contracts;

namespace AiReporting.Api.Application.AiReports.Orchestration;

public sealed class AiReportOrchestrator : IAiReportOrchestrator
{
    private readonly IReportIntentExtractor _intentExtractor;
    private readonly ISemanticQueryValidator _validator;
    private readonly IReportAuthorizationService _authorizationService;
    private readonly ISqlQueryBuilder _queryBuilder;
    private readonly IReportingQueryExecutor _queryExecutor;
    private readonly IForecastService _forecastService;
    private readonly ILlmReportWriter _reportWriter;
    private readonly ILogger<AiReportOrchestrator> _logger;

    public AiReportOrchestrator(
        IReportIntentExtractor intentExtractor,
        ISemanticQueryValidator validator,
        IReportAuthorizationService authorizationService,
        ISqlQueryBuilder queryBuilder,
        IReportingQueryExecutor queryExecutor,
        IForecastService forecastService,
        ILlmReportWriter reportWriter,
        ILogger<AiReportOrchestrator> logger)
    {
        _intentExtractor = intentExtractor;
        _validator = validator;
        _authorizationService = authorizationService;
        _queryBuilder = queryBuilder;
        _queryExecutor = queryExecutor;
        _forecastService = forecastService;
        _reportWriter = reportWriter;
        _logger = logger;
    }

    public async Task<AiReportResponse> GenerateAsync(AiReportRequest request, string userId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Prompt))
        {
            throw new ArgumentException("Prompt is required.");
        }

        var query = await _intentExtractor.ExtractAsync(request.Prompt, cancellationToken);
        _validator.Validate(query);
        await _authorizationService.AuthorizeAsync(userId, query, cancellationToken);

        var sql = _queryBuilder.Build(query);
        _logger.LogInformation("AI report request by {UserId}. Query={SemanticQuery}. Sql={Sql}", userId, JsonSerializer.Serialize(query), sql.Sql);

        var data = await _queryExecutor.ExecuteAsync(sql, cancellationToken);
        var forecast = await _forecastService.ForecastAsync(query, data, cancellationToken);
        var report = await _reportWriter.WriteAsync(query, data, forecast, cancellationToken);

        _logger.LogInformation("AI report generated by {UserId}. RowCount={RowCount}. ForecastRequested={ForecastRequested}", userId, data.Count, query.IncludeForecast);

        return new AiReportResponse
        {
            Query = query,
            Data = data,
            Forecast = forecast,
            Report = report
        };
    }
}
